# add c + bash?
language: haskell
ghc: 7.4
# php: 5.6
# node_js: 0.12

install:
  - cabal update
#  - cabal install --verbose=3 cabal-install

cache:
  directories:
    - $HOME/.cabal	# shellsheck-binary

# see http://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - bittorf@bluebottle.com
#   - kontakt@weimarnetz.de

# installing 'sloccount' and 'shellcheck' needs sudo
# maybe we should switch to selfcompile these
sudo: required

# if one fails, the build is marked b0rken
script:
  - 'openwrt-build/build.sh --travis_prepare'
  - 'openwrt-build/build.sh --check'
  - 'openwrt-build/build.sh --unittest'
