# https://docs.travis-ci.com/user/languages/
# https://github.com/travis-ci/travis-ci/issues/2856
language: php
php:
  - '5.6'

before_install:
- sudo apt-get update
- sudo apt-get install python3

# https://github.com/koalaman/shellcheck/issues/589
addons:
  apt:
    sources:
    - debian-sid	# Grab shellcheck from the Debian repo
#    packages:
#    - shellcheck       # seems included: https://github.com/koalaman/shellcheck/wiki/TravisCI
      
# see http://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - bb@npl.de
#   - kontakt@weimarnetz.de

# installing 'sloccount' and 'shellcheck' needs sudo
# maybe we should switch to selfcompile these
# also '/etc/kalua_init' needs somehow root (e.g. mount)
sudo: required

# if one fails, the build is marked b0rken
script:
  - 'openwrt-build/build.sh --travis_prepare'
  - 'openwrt-build/build.sh --check'
  - 'openwrt-build/build.sh --unittest'
