# see http://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - bittorf@bluebottle.com
    - kontakt@weimarnetz.de

# installing 'sloccount' and 'shellcheck' needs sudo
sudo: required

script: "openwrt-build/build.sh --check --unittest"
